default:
    type: "postgres"
    host: "192.168.149.120"
    port: 5432
    username: "postgres"
    password: "123qwe"
    database: "next"
    entities:
        - '**/*.entity.js'
    migrations:
        - '**/*.migration.js'
    logging: true
    migrationsRun: false
    synchronize: true
